### ISSUE TITLE
getImageUrl sub-domain mismatch

### ISSUE THREAD

**Issue by dnm13** [H2Owater425/node-hitomi#10]
I ran another test again using this module. This time I tried using getImageUrl which should return the correct url for the file / image.

I don't know the logic behind this function, nor I know the logic behind hitomi's sub domain system. So I doubt I'll be able to give out details for this issue. But here's what I've tried.

```typescript
import { getGalleryData, getImageUrl } from 'node-hitomi'
import axios from 'axios'

async function getImage(link: string): Promise<Buffer> {
  return new Promise(async (res, rej) => {
    await axios.get(link, {
      headers: { referer: "https://hitomi.la" },
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      responseType: "arraybuffer"
    })
      .then((r) => { res(r.data) })
      .catch(err => rej(err))
  })
}

getGalleryData(1954101)
  .then(async (gallery) => {
    for (let i = 0; i < gallery.files.length; i++) {
      var url = getImageUrl(gallery.files[i], 'jpg'), valid = false;
      await getImage(url).then(buffer => { /* ignore buffer for now */ valid = true }).catch(err => { valid = false })
      console.log(`page ${i}: ${url} (valid: ${valid})`);
    }
  })
```

Here's the result
![image](https://user-images.githubusercontent.com/56634278/127647073-1d7325bb-e26c-4f55-8660-ee9ca634a00b.png)
Notice that valid with value as `true` means the url is correct and getImage function were able to fetch image, while `false` means the url were incorrect and site returning 404 not found, thus axios rejecting the promise.

This happen on all gallery I've tried. So I get curious and directly check the image from browser, and found out it's the sub-domain mismatch
![image](https://user-images.githubusercontent.com/56634278/127647400-42cfceba-9868-4d66-8e47-c589576fa69a.png)
module version used: v 2.0.0

**Comment by H2Owater425** [comment]
I found error, and it's pretty big...
My understanding of subdomain was adding b as first character if image's extension is jpg or png, but it was wrong.
I must reverse engineer hitomi reader again first to solve this problem, it won't be long.

**Comment by H2Owater425** [comment]
Okay, I just checked that hitomi rewrote it's subdomain-creating logic.
I think I have to examine again to write the code, since it is too late in my time zone, I'll do it later.

**Comment by dnm13** [comment]
> Okay, I just checked that hitomi rewrote it's subdomain-creating logic.
> I think I have to examine again to write the code, since it is too late in my time zone, I'll do it later, sorry...

don't worry about rushing it
and you've done nothing to apologize for

**Comment by H2Owater425** [comment]
I found what's wrong with them, Hitomi used to use the number of frontends to get the first letter of the subdomain, but recently they changed that into a meaningless number.
I test new the re-written code and worked well, as I said in another issue (#11), a new feature premeditated at #8 will be added with the bug fix.

![image](https://user-images.githubusercontent.com/50160366/127728005-4a15db10-29e0-478b-84ef-c6b8cd9b0d96.png)

**Comment by H2Owater425** [comment]
Even there's been a lot of big ups and downs, the new version of the package has finally been released!
Thanks for noticing me about the errors to let me fix them, here's the changelog (and what I have done wrong 😥) about this update [Release node-hitomi@3.0.1 · H2Owater425/node-hitomi](https://github.com/H2Owater425/node-hitomi/releases/tag/3.0.1)!

**Comment by dnm13** [comment]
![image](https://user-images.githubusercontent.com/56634278/127750484-0ece5dee-7a89-4d29-9a93-72f5fdd9c306.png)
great job!
it works properly now, thanks for fixing it :)

**Comment by dnm13** [comment]
it occasionally would return invalid / wrong sub domain
![image](https://user-images.githubusercontent.com/56634278/132950007-305fb567-9033-4b9c-946b-837758b41b7e.png)

from browser inspect:
![image](https://user-images.githubusercontent.com/56634278/132950037-3ec39316-d1cd-4019-bf6a-b243a7dac231.png)

you can check it from code 1989850 page 47 (the picture said 46 but it's because index start from 0)
going to reopen the issue with this comment. hopefully you can fix it

**Comment by H2Owater425** [comment]
I guess Hitomi recently changed its method to get the subdomain of the image again. I'll examine Hitomi's code as soon as I get arrived at home.

**Comment by H2Owater425** [comment]
![화면 캡처 2021-09-12 183940](https://user-images.githubusercontent.com/50160366/132982896-1d9b0068-ce04-45fb-b27c-e74ee25e3bbe.png)
I released a new release with few bug fixes including this one, please check it out!
[Release node-hitomi@4.2.0 · H2Owater425/node-hitomi](https://github.com/H2Owater425/node-hitomi/releases/tag/4.2.0)

**Comment by dnm13** [comment]
![image](https://user-images.githubusercontent.com/56634278/132986435-c014d6e1-33a8-424b-a590-f9bbc6137c88.png)
works like charm
thanks for the quick fix! much appreciated :)
