### ISSUE TITLE
Default export error: The expression of an export assignment must be an identifier or qualified name in an ambient context.

### ISSUE THREAD

**Issue by dnm13** [H2Owater425/node-hitomi#11]
Something's wrong with the default export.

The error occurs only with just importing / calling the module.

![image](https://user-images.githubusercontent.com/56634278/127647793-b3767404-2c84-4167-989f-dde8202ece7f.png)

**Comment by H2Owater425** [comment]
Sorry, since I tried to solve the problem as fast as I could, I haven't tested my module in javascript.
I found a solution for that, so a new release of the package with a new feature will solve this problem.
Please wait for then.

**Comment by dnm13** [comment]
> Sorry, since I tried to solve the problem as fast as I could, I haven't tested my module in javascript.
> I found a solution for that, so a new release of the package with a new feature will solve this problem.

it's okay. do your best
