### ISSUE TITLE
When use 'getIds' or 'getQueriedIds', throw REQUEST_REJECTED

### ISSUE THREAD

**Issue by bass9030** [H2Owater425/node-hitomi#39]
## Environment
* OS: Windows 10 21H1 build 19043.1466
* Nodejs: v16.13.2
* Npm: 8.3.1

## Code
```js
const page = parseInt(req.query.page) || 1;
if(page == 1) {
    const result = await hitomi.getIds({
        startIndex: 0,
        endIndex: 9
    })
    res.json(result);
}else{
    const result = await hitomi.getIds({
        startIndex: (page - 1) * 10,
        endIndex: (page - 1) * 10 + 9
    })
    res.json(result);
}
```
```js
const result = await hitomi.getQueriedIds([{"type": "female","name": "sole_female"}]);
res.json(result);
```
## Error message
```
// hitomi.getIds(...)
HitomiError [REQEUST_REJECTED]: Request to 'https://ltn.hitomi.la/index-all.nozomi' was rejected
    at ClientRequest.<anonymous> ([project_dir]\node_modules\node-hitomi\library\index.js:1:5326)
```
```
// hitomi.getQueriedIds(...)
HitomiError [REQEUST_REJECTED]: Request to 'https://ltn.hitomi.la/n/tag/female:sole female-all.nozomi' was rejected
    at ClientRequest.<anonymous> ([project_dir]\node_modules\node-hitomi\library\index.js:1:5326)
```

I try to connect above url to web browser and it show '403 Forbidden'.
And i try to connect same url with Referer header, it's working.
So i think requesting to 'ltn.hitomi.la/*.nozomi' required referer header set as 'https://hitomi.la'.

(Sorry to my dirt English. I'm student in Korea, so i not good at English)

**Comment by H2Owater425** [comment]
Thank you for the bug report with very detailed information!
I recently noticed that Hitomi is reinforcing its API rule
Following your advice, I will add the URL of the Hitomi in the referer header as the default
Again, thank you for your contribution to this package!
(P.S. In the next major version, I will combine features of getQueriedIds and getIds in one, I think)

자세한 정보와 함께 버그를 보고해주셔서 감사합니다!
저도 최근에 히토미 api 규칙이 좀 빡빡해지고 있다는걸 알아냈습니다
조언에 따라 referer 헤더에 히토미 주소를 기본으로 넣도록 하겠습니다
다시 한번, 이 페키지에 기여해주셔서 감사합니다!
(추신: 아마 다음 주요 버전에서 getQueriedIds와 getIds의 기능을 합칠 것 같습니다, 고등학교 입학 과제가 있어서 개발 속도가 좀 느려졌네요
최대한 빨리 사용하실 수 있는 버전으로 만나 뵙겠습니다!)

**Comment by H2Owater425** [comment]
Just released a new version, please check it out!

방금 새로운 버전을 출시했습니다, 확인해주세요!
