### ISSUE TITLE
Hitomi only supports extension of webp, avif, jxl and mp4 only from now on

### ISSUE THREAD

**Issue by H2Owater425** [H2Owater425/node-hitomi#46]
They have been gradually changing their image url system from the thumbnail, and eventually they dropped support for the extensions except for webp, avif, and mp4.
![image](https://user-images.githubusercontent.com/50160366/154852128-97008fec-36ac-4b11-9f2c-951c3e4abc95.png)

**Comment by Sentimeit** [comment]
good, I would like to know if it is deliberate that hitomi now downloads everything in webp or is it just a mere error on the page and if it is an error they expect a solution soon and if it is not an error why did they drastically decide to do this?

**Comment by H2Owater425** [comment]
> good, I would like to know if it is deliberate that hitomi now downloads everything in webp or is it just a mere error on the page and if it is an error they expect a solution soon and if it is not an error why did they drastically decide to do this?

First, yeah, Hitomi will use webp format for every image with the addition of avif format for some images, and I guess it's their intentional decision.
Since webp format has the advantage of 30 to 35 percent over jpg and png in file size, I think they would like to use webp format to save their resources.
They were using webp and avif format only for thumbnails.
So, if there's a change, I'll make a notice here as soon as I'll announce it here.

**Comment by sacchier** [comment]
I contacted Hitomi from the whois site as soon as the webp conversion started in early February. I asked them to stop webp or consider a different means of making the original available. But by March, there was no change. 

Probably because many upload sites were forced to shut down. Perhaps that is why so many people searched for similar sites and found hitomi. This resulted in a heavy load on hitomi. So we had no choice.

HITOMI is a very good site because it does not require account registration, has no limit on daily usage, and can store original data. I have looked for an alternative site but could not find one.

I have no choice but to believe and wait. But if you really want to take action, the only way is to send an indirect email request to hitomi from the whois site.

**Comment by Sentimeit** [comment]
thanks for the answer, I did not expect such a drastic change to be
intentional, many people visited hitomi for the possibility of quickly
downloading authors in their original format, I think that by doing this
they will have lost a large part of their consumers

**Comment by Sentimeit** [comment]
could you send me a link to be able to send him that message I think I
could gather enough people to make a massive request since many pages were
affected in turn by the hitomi change

**Comment by FluffyDiscord** [comment]
@H2Owater425 many pictures are still available only in jpg/png or as a gif (for some reason) we still NEED to have a fallback extension, for example gallery id 2175679 file/image index 1698 has only JPG

**Comment by H2Owater425** [comment]
> @H2Owater425 many pictures are still available only in jpg/png or as a gif (for some reason) we still NEED to have a fallback extension, for example gallery id 2175679 file/image index 1698 has only JPG
> 
> https://zerobin.net/?fa109bc2d0b036c7#APeQJ/F774whrE0lfaaZF9azxMiWLa4oZBRw2ekDw1w=

First of all, thank you for reporting your problem.

However, since Hitomi changed its image url generating logic to bypass webp and avif availability, regardless of its hasAvif and hasWebp value, the image is processed in webp and avif logic.

But, this could be changed since I noticed this fact a long time ago, so let me check if is there any changes in their code.

P.S. it could take some time because I'm in the midterm exam period, I'm sorry but please wait.

**Comment by H2Owater425** [comment]
![image](https://github.com/H2Owater425/node-hitomi/assets/50160366/dca2e518-f91e-4c01-8c2b-cf80353264af)
They added new file for images called JPEG XL (.jxl)
