### ISSUE TITLE
getTags with artist(and group, series, character), return blank array

### ISSUE THREAD

**Issue by senosa** [H2Owater425/node-hitomi#49]
## Description of bug
getTags with

- artist
- group
- series
- character

 return blank array.
other types (ex. female, language...) are OK.

```javascript
const hitomi = require("node-hitomi").default;

hitomi.getTags("female", { startWith: "z" }).then((value) => {
  console.log(value); // OK, 2 tags are returned.
});

// getTags with artist(and group, series, character), return blank array.
hitomi.getTags("artist", { startWith: "z" }).then((value) => {
  console.log(value); // NG, blank array.

  // getTagUrl return valid URL: https://ltn.hitomi.la/allartists-z.html
  console.log(hitomi.getTagUrl("artist", { startWith: "z" }));
});
```

getTagUrl return valid URL, so I guess reason of this result is this line,

https://github.com/H2Owater425/node-hitomi/blob/cdaff690294b90cb28136c59f1c86a62527dccbf/source/index.ts#L684

but I can't read these regular expression correctly...

## Expected behavior
return valid tags array.

## Screenshots
![screenshot-2022-05-16-163723](https://user-images.githubusercontent.com/203887/168542926-254cf3d1-67b3-4767-b8b9-1d293765afd6.png)

## Environment
- OS: macOS Monterey 12.3.1
- Version
  - NodeJS: 16.14.2
  - Package: 7.0.3

**Comment by H2Owater425** [comment]
I just released a new release, please check it out for [the package's new version](https://www.npmjs.com/package/node-hitomi).
And please let me know if there's any error afterward, thank you for your contribution!

**Comment by senosa** [comment]
It's working as expected.
Thank you for quick and perfect work!
