### ISSUE TITLE
getTags can't find artists include dot character

### ISSUE THREAD

**Issue by senosa** [H2Owater425/node-hitomi#50]
## Description of bug
getTags can't find artists include dot character.
Other types (group, tag, series...) too.

```javascript
const main = async () => {
  const resp = await hitomi.getTags("artist", { startWith: "0-9" });
  // missing `.357-inch` and `.s`
  console.log(resp.slice(0, 5));
  // =>
  // [
  //   { type: 'artist', name: '-1semuy' },
  //   { type: 'artist', name: '0-g' },
  //   { type: 'artist', name: '0-jirow' },
  //   { type: 'artist', name: '007' },
  //   { type: 'artist', name: '013' }
  // ]
};
```

## Environment
- OS: macOS Monterey 12.3.1
- Version
  - NodeJS: 16.14.2
  - Package: 7.0.4

**Comment by H2Owater425** [comment]
Sorry for the delay, I couldn't check github and mail recently.
I just finished writing new code and testing it out, and it worked fine (I guess).
Anyway, I released a new release a minute ago, please check it out for [the package's new version](https://www.npmjs.com/package/node-hitomi).

**Comment by senosa** [comment]
👌
