### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by ThanhPham99** [H2Owater425/node-hitomi#58]
## Description of bug
Got connect timeout when using hitomi.getGalleryIds({})
Error: connect ETIMEDOUT 23.237.54.194:443
Error: connect ETIMEDOUT 23.237.107.210:443

## Screenshots
![image](https://github.com/H2Owater425/node-hitomi/assets/45620091/7d57b02e-696f-4f7e-b6a7-54ffa9c3cf51)

## Environment
- OS: Ubuntu Server 22 LTS 64-bit
- Version
  - NodeJS: v20.12.2
  - Package: 10.5.0

**Comment by H2Owater425** [comment]
Thank you for using this package and reporting the issue.

However, it seems that the version of the included package is higher than the latest version available.
To make things clear, I want you to recheck the version while verifying your internet connection. (ex: connection blocked by external factors)

Please let me know if there is anything else I can help you with.

**Comment by ThanhPham99** [comment]
Everything is working well now. Maybe this issue caused by internet connection.
