### ISSUE TITLE
Cannot find any gallery id if title contains only English letters

### ISSUE THREAD

**Issue by monsterakill** [H2Owater425/node-hitomi#59]
## Description of bug

So if i try to find any gallery not in English hitomi.getGalleryIds working fine, but finds nothing if title contains only English letters

## Screenshots

Doesn't find anything (title: 'SACRED SAGA Postcard Set' //id - 2892056)
![изображение](https://github.com/user-attachments/assets/c7d94aa7-cb46-4a57-857e-87a512682f6d)

Works fine (title: '蝈蝈的概念艺术 商业游戏概念设计流程解析' //id - 2726680)
![изображение](https://github.com/user-attachments/assets/c1813def-e881-478e-9aca-b38da50316bb)

## Environment
- OS: Windows 10
- Version
  - NodeJS: 22.4.0
  - Package: 8.0.2

**Comment by H2Owater425** [comment]
I just published a [new version](https://www.npmjs.com/package/node-hitomi/v/8.0.3), and I hope it works as you expected.
If there are any problems, please let me know so that I can fix them.
As always, thanks for contributing to this repository.
