### ISSUE TITLE
getParsedTags() space issue

### ISSUE THREAD

**Issue by frontishobby** [H2Owater425/node-hitomi#60]
## Description of bug
- getParsedTags() 에서 띄어쓰기를 포함한 태그의 경우 현재 언더바(_) 로 바꿔주고 있음
- 그러나 해당 Tag 를 넣고 getGalleryIds 호출 시 요청 거부됨
- 체크해보니 hitomi 에서는 공백 넣고 urlencode 하는중
<img width="538" alt="image" src="https://github.com/user-attachments/assets/ffe54998-8b62-442e-a2c3-3225a5df8de3">

```javascript
const tags = hitomi.getParsedTags(tagString)

for (let i = 0; i < tags.length; i++) {
    tags[i].name = tags[i].name.replaceAll('_', ' ')
}
```

따라서 상단 코드처럼 강제로 name 바꿔줄 시 workaround 가능

## Expected behavior
- getParsedTags 에서 공백을 언더바가 아닌 공백 그대로 사용하도록 하여, getGalleryIds 가 정상적인 응답을 가져오도록

## Screenshots
<img width="983" alt="image" src="https://github.com/user-attachments/assets/3c9f46c4-3c92-4b61-98b0-33adebd959bc">
그냥 호출 시 발생하는 에러

## Environment
- OS: Termux
- Version
  - NodeJS: 21.6.2
  - Package: 8.0.2

## Additional context
- 여유 없으시면 제가 수정해서 PR 올릴게요~
- 비슷하게 태그 검색도 동작 안하는듯 싶은데 좀더 자세히 보고 리포트 하겠습니다.

**Comment by H2Owater425** [comment]
버그 제보 감사드립니다
방금 수능치고 나온지라 최대한 빨리 확인해보겠습니다!

**Comment by H2Owater425** [comment]
> 캬 고생하셨습니다! 푹 쉬세요!
> 
> 아 그리고 추가 궁금증이 있는데 syncronize 호출 주기가 어떻게 되나요?

결론부터 말씀드리자면 아직 알아내지는 못했습니다.
실사용 시에는 이미지 요청에 Not Found 응답이 돌아왔을 때 synchronize를 호출해주시는 것이 최선의 방법이지 않을까 싶습니다.

이전에는 일정한 규칙에 따라 서브도메인과 경로가 결정되어서 웹사이트가 업데이트될 때마다 라이브러리에 이를 적용했습니다.
개발자가 이 라이브러리를 의식했는지는 모르겠지만 언젠가부터는 한 파일에 가능한 모든 경우의 수를 하드코딩하는 방식으로 바뀌었더라고요.

그 이후로는 이슈가 생길 때마다 수작업으로 바꾸는 대신 이미지 주소를 얻기 전에 해당 파일을 분석해서 필요한 정보를 저장해두는 방식으로 구조를 변경했습니다.
구현해둔 이후에는 학업이 바빠서 변경 주기라던가 자세한 내용은 파악하지 못했네요.

이제는 남는 게 시간이다 보니 추가적으로 정보를 얻게 된다면 리드미라던가 레포지토리 위키에 관련 내용을 적어둘 수 있도록 해보겠습니다!

**Comment by frontishobby** [comment]
히토미 관리자도 많은 API에 시달렸나 보네요.. 답변 감사합니다!

**Comment by H2Owater425** [comment]
방금 [새로운 버전](https://www.npmjs.com/package/node-hitomi/v/8.0.4)을 출시했습니다
아마 내부적으로 사용하는 getNozomiUri 함수에서 주소를 생성할 때 언더바가 있는 태그에 대한 예외 처리가 없어서 이 함수를 이용해서 주소를 생성하는 모든 함수에 영향이 갔던 것 같네요
혹시나 추가적인 문제가 있다면 언제든지 편하게 말씀해주시면 감사하겠습니다!

**Comment by frontishobby** [comment]
정상 동작 확인했습니다! 빠른 대응 감사합니다!

**Comment by frontishobby** [comment]
이거 문제가 있어요! 히토미에서 어떤 로직인지는 모르겠는데, female, male 등은 공백을 넣었을 때 정상동작하고, tag, series 등은 언더바를 넣어야 정상동작하네요..! 😰

**Comment by H2Owater425** [comment]
제가 코드 베이스를 마지막으로 본지 너무 오래되어서 수정 방향을 잘못 잡았던 것 같습니다
getParsedTags의 태그 추가 단계에서부터 밑줄을 띄어쓰기로 수정하는 [새로운 버전](https://www.npmjs.com/package/node-hitomi/v/8.0.5)을 출시했습니다
번거로우시겠지만 다시 한번 확인해주시면 감사하겠습니다

**Comment by frontishobby** [comment]
해결 확인했습니다! 빠른 패치 감사합니다.
