### ISSUE TITLE
 t.Agent is not an object or null

### ISSUE THREAD

**Issue by Abolfazl2049** [H2Owater425/node-hitomi#62]
## TypeError: class heritage t.Agent is not an object or null
im using  nuxt 3 and ssr is off
![Screenshot 2024-12-18 223925](https://github.com/user-attachments/assets/5aa4e812-c92d-4367-bd9e-4780ae065f7c)

## Environment
- Version
  - NodeJS:  latest
  - Package: latest

**Comment by H2Owater425** [comment]
This library does not support web environment, please ensure that the code calling this library is running on the server side.
